### ISSUE TITLE
`apigentools generate --clone-repo` does not work

### ISSUE THREAD

**Issue by ep1cman** [DataDog/apigentools#185]
**Overview of issue:**
When running `apigentools generate --clone-repo` an error occurs

**Steps to reproduce the issue:**
1. `apigentools generate --clone-repo` 

**Describe the results you received:**
```
❯ apigentools generate --clone-repo
zsh: correct 'generate' to 'generated' [nyae]? n
INFO: Generated spec/v1/full_spec.yaml for nodejs-express-server/v1
Traceback (most recent call last):
  File "/Users/sebgos01/.pyenv/versions/3.8.0/bin/apigentools", line 11, in <module>
    load_entry_point('apigentools', 'console_scripts', 'apigentools')()
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Volumes/Projects/Zen of Design/apigentools/apigentools/commands/generate.py", line 96, in generate
    run_command_with_config(GenerateCommand, ctx, **kwargs)
  File "/Volumes/Projects/Zen of Design/apigentools/apigentools/commands/command.py", line 41, in run_command_with_config
    click_ctx.exit(cmd.run())
  File "/Volumes/Projects/Zen of Design/apigentools/apigentools/commands/generate.py", line 275, in run
    self.pull_repository(language_config, branch=self.args.get("branch"))
  File "/Volumes/Projects/Zen of Design/apigentools/apigentools/commands/generate.py", line 315, in pull_repository
    output_dir = language.generated_lang_dir
  File "/Volumes/Projects/Zen of Design/apigentools/apigentools/config.py", line 287, in generated_lang_dir
    return os.path.join(constants.SPEC_REPO_GENERATED_DIR, self.github_repo)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/sebgos01/.pyenv/versions/3.8.0/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError('%s() argument must be str or bytes, not %r' %
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Describe the results you expected:**
The repo to be pulled and the code be be generated inside it

**Additional information you deem important (e.g. issue happens only occasionally):**
The LanguageConfig class is not getting values for `github_repo` and `github_org`. The cause seems to be the `Config` class here: https://github.com/DataDog/apigentools/blob/master/apigentools/config.py#L157
Removing it fixes everything and it works as expected

**Comment by ep1cman** [comment]
Ah, now that I look at it again I was using `github_repo` in my YAML not `github_repo_name`
